# This workflow will run npm build and then publish to gh-pages branch

name: npm Deploy to GH Pages

on:
  push:
    branches: 
      - 'master'

jobs:
  publish-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install --legacy-peer-deps
          npm run build
          git checkout -B gh-pages
          mv dist/ .dist/
          rm -rf *
          cp -r .dist/* .
          rm -r .dist/
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated Build for gh-pages on $(date)"
          git push --set-upstream origin gh-pages
