# This workflow will run npm build and then publish to gh-pages branch

name: npm Deploy to GH Pages

on:
  push:
    branches: 
      - 'master'

jobs:
  publish-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run
      - uses: actions/checkout@v4
          with:
            ref: gh-pages
      - run: a
